nervosnetwork/ckb-cli

- src/subcommands/wallet/index.rs
> fix: jsonrpc-client thread leak

- ckb-index/src/index/key.rs
- ckb-index/src/index/types.rs
- fix forgot remove type script hashes (type hash + code hash) when cell is dead
- fix handle hash keys the wrong way.
> fix: Fix index handle type script hashes bug

- README.md
- src/subcommands/account.rs
- src/subcommands/wallet/mod.rs
* Remove plural from sub-command messages
* Update README
> Subcommand message

- Cargo.lock
- Cargo.toml
- ckb-index/Cargo.toml
- ckb-sdk/Cargo.toml
- ckb-sdk/src/wallet/bip32.rs
- src/subcommands/util.rs
- src/utils/yaml_ser.rs
```
util serialize-tx
util deserialize-tx 
util serialize-script
util deserialize-script
```
> feat: Add serialization utils sub-commands

- Cargo.lock
- Cargo.toml
- ckb-sdk/src/chain.rs
- ckb-sdk/src/lib.rs
- src/subcommands/wallet/mod.rs
- src/utils/arg.rs
- src/utils/mod.rs
* feat: Support NervosDAO deposit/withdraw
* refactor: Move command args of wallet out
* refactor: Modular some functions
> feat: Support dao transaction

- src/subcommands/util.rs
```
CKB> util difficulty-to-compact --difficulty 0x1194063f9e3
compact-target: 0x1be90400
CKB> util compact-to-difficulty --compact-target 0x1c00e904
difficulty: 0x1194063f9e3
```
> feat: Add compact-target/difficulty conversion subcommands

- ckb-sdk/src/wallet/keystore/mod.rs
- src/subcommands/account.rs
* Add a field into keystore, `"origin: ckb-cli"`
* Do not output the path of keystore
> feat: Remark keystore origin

- ckb-sdk/src/basic.rs
- ckb-sdk/src/lib.rs
- ckb-sdk/src/multisig_addr.rs
- src/subcommands/util.rs
```
./target/debug/ckb-cli util single-to-multisig-addr --address ckb1qyq8nry7w47zqmzqc8r7shk2fut0pz8w072qht72mw --locktime 2019-11-01
"ckb1qyq8nry7w47zqmzqc8r7shk2fut0pz8w072qht72mw,2019-11-01,ckb1q3w9q60tppt7l3j7r09qcp7lxnp3vcanvgha8pmvsa3jplykxn32syzv6uxr48nlw0ffcxk0jn0kuz3np9t5cqqqqqqqqqgqyqfsmw7c"
```
> feat: Convert singlesig addr to multisig-1of1 addr

- .travis.yml
> chore: static link openssl in macOS package

- ckb-sdk/src/constants.rs
- ckb-sdk/src/lib.rs
- ckb-sdk/src/rpc/client.rs
- ckb-sdk/src/rpc/mod.rs
- ckb-sdk/src/rpc/primitive.rs
- ckb-sdk/src/rpc/types.rs
- ckb-sdk/src/types/human_capacity.rs
- ckb-sdk/src/types/since.rs
- src/interactive.rs
- src/main.rs
- src/subcommands/mock_tx.rs
- src/subcommands/rpc.rs
- src/subcommands/tui/mod.rs
- src/subcommands/tui/state.rs
- src/subcommands/util.rs
- src/subcommands/wallet/index.rs
- src/subcommands/wallet/mod.rs
- src/utils/other.rs
* `header.timestamp`
* `header.number`
* `header.epoch`
``` yaml
version: 0
compact_target: 0x1d435e16
timestamp: "1576078392848 (2019-12-11 23:33:12.848 +08:00)"
number: 78200
epoch: "0x2f10285000050 {number: 80, index: 645, length: 753}"
parent_hash: 0x4f8c2a0b3f6b2a0077d0f127da330357208b631a4f6663ecd91467cd34873f60
transactions_root: 0x985629432da796b237f05c16e6af3f02050df443a414232b95385c560013e91f
proposals_hash: 0x0000000000000000000000000000000000000000000000000000000000000000
uncles_hash: 0x0000000000000000000000000000000000000000000000000000000000000000
dao: 0xae0db9f9d9d6e92e0f87f20f59942300cde0bfb6c8fd0e0000c8c64445b70007
nonce: 0x68c60ee7e37c67d209e285346f66f146
hash: 0xf049752cad0f0faa527a8893d2e7befb1b40f450face6951a7e76393e353663a
```
* `tx.inputs.since`
* …
> feat: Human readable fields (capacity, timestamp, epoch, since)

- ckb-sdk/src/rpc/client.rs
- test/Cargo.toml
- test/src/app.rs
- test/src/main.rs
- test/src/miner.rs
- test/src/setup.rs
- test/src/spec/mod.rs
- test/src/spec/rpc.rs
- test/src/util.rs
Split from https://github.com/nervosnetwork/ckb-cli/pull/159
> feat: impl a basic testing framework

- Cargo.lock
- Cargo.toml
- ckb-sdk/src/lib.rs
- src/interactive.rs
- src/main.rs
- src/subcommands/dao/builder.rs
- src/subcommands/dao/command.rs
- src/subcommands/dao/mod.rs
- src/subcommands/dao/util.rs
- src/subcommands/mod.rs
- src/subcommands/wallet/mod.rs
- src/utils/arg.rs
- src/utils/arg_parser.rs
- src/utils/other.rs
- test/src/main.rs
- test/src/setup.rs
- test/src/spec/dao.rs
- test/src/spec/mod.rs
Support DAO and do some refactoring.
* Move `dao` commands out from `wallet`. Type `ckb-cli dao --help` for commands detail.
Example: 
```
CKB> dao deposit --capacity 102 --tx-fee 1 --privkey-path /Users/apple/ckb-testing/bank0
0x8c056e08d23930fb3348f615549be4a21914b872c10d9ffda822e0573ff890c6
CKB> dao query-deposited-cells --lock-hash 0x32e555f3ff8e135cece1351a6a2971518392c1e30375c1e006ad0ce8eac07947
live_cells:
- capacity: 10200000000
data_bytes: 8
index:
output_index: 0
tx_index: 1
lock_hash: 0x32e555f3ff8e135cece1351a6a2971518392c1e30375c1e006ad0ce8eac07947
number: 383
tx_hash: 0x8c056e08d23930fb3348f615549be4a21914b872c10d9ffda822e0573ff890c6
tx_index: 0
type_hashes:
- 0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e
- …
```
> feat: 2 phase dao

- src/subcommands/dao/util.rs
- test/src/main.rs
- test/src/spec/dao.rs
Fix 2 bugs within `calculate_dao_maximum_withdraw`:
* The position of deposit cell
* The amount of compound
> fix: Fix calculate dao maximum withdraw

- Cargo.lock
- Cargo.toml
- Makefile
- ckb-index/Cargo.toml
- ckb-sdk-types/Cargo.toml
- ckb-sdk/Cargo.toml
- devtools/azure/windows-dependencies.yml
- test/Cargo.toml
> Update ckb to v0.27.1

- src/subcommands/dao/command.rs
- src/subcommands/dao/mod.rs
- src/subcommands/dao/util.rs
- src/subcommands/wallet/mod.rs
- src/utils/other.rs
* Improve command line argument checker for dao subcommand
* Remove duplicated functions
> chore: Improve dao subcommand

- README.md
All second level sub-commands are listed in [wiki page](https://github.com/nervosnetwork/ckb-cli/wiki/Sub-Commands).
> docs: Update README for sub-commands listing

- Cargo.lock
- Cargo.toml
- docs/API-Server.md
- src/main.rs
- src/subcommands/api_server.rs
- src/subcommands/mod.rs
- src/subcommands/wallet/mod.rs
- src/utils/arg.rs
- src/utils/other.rs
```
export RUST_LOG=ckb_cli=info 
ckb-cli --url http://localhost:8114 server --privkey-path xxx.privkey
```
Documentation: https://github.com/TheWaWaR/ckb-cli/blob/advanced-api-server/docs/API-Server.md
> feat: Add an api server sub-command (jsonrpc)

- src/subcommands/molecule.rs
Currently molecule encode/decode with invalid data structure.
> fix: Fix molecule encode/decode Block/UncleBlock bug

- src/main.rs
- src/subcommands/util.rs
```
ckb-cli util completions bash > /etc/bash_completion.d/ckb-cli.bash-completion
```
> feat: generates completion scripts for shell

- Cargo.lock
- Cargo.toml
- src/interactive.rs
- src/main.rs
- src/subcommands/account.rs
- src/subcommands/api_server.rs
- src/subcommands/dao/command.rs
- src/subcommands/mock_tx.rs
- src/subcommands/molecule.rs
- src/subcommands/rpc.rs
- src/subcommands/tx.rs
- src/subcommands/util.rs
- src/subcommands/wallet/mod.rs
- src/utils/arg.rs
- src/utils/arg_parser.rs
- src/utils/completer.rs
- test/Cargo.toml
- test/src/app.rs
Clap [3.0 change log](https://github.com/clap-rs/clap/blob/master/v3_changes.md)
> chore: Bump up clap to 3.0.0-beta.1

- src/interactive.rs
- src/main.rs
- src/subcommands/api_server.rs
- src/subcommands/dao/mod.rs
- src/subcommands/wallet/mod.rs
- src/utils/config.rs
- test/src/setup.rs
BREAKING CHANGE:  Now default sync index db to tip
fix #292
fix #281
> fix: Default sync index db to tip

- ckb-sdk/src/tx_helper.rs
Should not sign inputs with unexpected lock script.
> fix: Fix tx_helper skip check bug

- Cargo.lock
- ckb-index/Cargo.toml
Close https://github.com/nervosnetwork/ckb-cli/issues/297
> chore(deps): bump rocksdb from 0.12.3 to 0.13

- src/subcommands/dao/command.rs
It's a bug of clap, otherwise if `<privkey-path>` is not given `<from-account>` must required.
The bug only happen when put `<tx-fee>` before `<out-point>`.
fix #302
> fix: Fix dao subcommands parse argument bug

- ckb-sdk/src/tx_helper.rs
Forgot sign witnesses without corresponding inputs.
> fix: Fix sign transaction bug

- src/main.rs
- test/src/main.rs
```bash
$ export CKB_CLI_HOME=/tmp/ckb-cli
$ ckb-cli
```
Related issue: https://github.com/nervosnetwork/ckb-cli/issues/283
> feat: Customize ckb-cli home directory

- ckb-index/src/index/types.rs
- docs/API-Server.md
- src/subcommands/dao/mod.rs
BREAKING CHANGE: Rename field from LiveCellInfo.tx_index to LiveCellInfo.output_index
> refactor: Rename LiveCellInfo.tx_index to output_index

- ckb-sdk-types/src/transaction.rs
- ckb-sdk/src/transaction.rs
- src/subcommands/mock_tx.rs
If `CellMeta::transaction_info` field is `None`, when script load header by input will panic. Related [CKB code](https://github.com/nervosnetwork/ckb/blob/a86509e8874aeb127d9960da08ce4bd2bf1a93c8/script/src/syscalls/load_header.rs#L48-L51):
```rust
fn load_header(&self, cell_meta: &CellMeta) -> Option<HeaderView> {
let block_hash = &cell_meta
.transaction_info
.as_ref()
.expect("block_info of CellMeta should exists when load_header in syscall")
.block_hash;
if self
.header_deps
.clone()
.into_iter()
.any(|hash| &hash == block_hash)
{
self.data_loader.get_header(&block_hash)
} else {
None
}
}
```
So we put a `block_hash` in `MockCellDep` and `MockInput` to indicate that the cell is included in that block.
**NOTE**: JSON file is compatible with old version, since the `block_hash` field is …
> fix: Fix Load header by input/cell_dep bug in mock-tx sub-command (missing block_hash field)

- src/subcommands/mock_tx.rs
For debug purpose when use [`ckb-debugger`](https://github.com/xxuejie/ckb-standalone-debugger)
Usage:
```bash
$ ckb-cli mock-tx dump --help
Dump all on-chain data(inputs/cell_deps/header_deps) into mock_info
USAGE:
ckb-cli mock-tx dump [FLAGS] [OPTIONS] --tx-file <tx-file>
OPTIONS:
--tx-hash <tx-hash>                The hash of transaction which is on the chain
--tx-file <tx-file>                CKB transaction data file (format: json)
--output-file <output-file>        Dumped mock transaction data file (format: json)
$ ckb-cli mock-tx dump --tx-hash 0x9437f7049c5209e05d843e2b826ad3523b7790bc5b450ab0fe051a56ab76d850 --output-file mock-tx.json
$ ckb-cli mock-tx verify --tx-file mock-tx.json
cycle: 1692424
tx-hash: 0x9437f7049c5209e05d843e2b826ad3523b7790bc5b450ab0fe051a56ab76d850
```
> feat: Add a sub-command to mock-tx for dump standalone mock transaction

- Cargo.lock
- Cargo.toml
- Makefile
- ckb-index/Cargo.toml
- ckb-sdk-types/Cargo.toml
- ckb-sdk-types/src/transaction.rs
- ckb-sdk/Cargo.toml
- ckb-sdk/src/rpc/client.rs
- ckb-sdk/src/rpc/types.rs
- plugin-protocol/Cargo.toml
- src/subcommands/rpc.rs
- test/Cargo.toml
- test/src/spec/plugin.rs
* Update ckb to v0.35.0-rc1
* Update json rpc data structures
* Add more json rpc methods
* Add more json rpc subcommands
> chore: Update ckb to v0.35

- src/subcommands/util.rs
```
CKB> util cell-meta --tx-hash 0xa563884b3686078ec7e7677a5f86449b15cf2693f3c1241766c6996f206cc541 --index 1
address: ckt1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqparrr6
data_hash: 0x709f3fda12f561cfacf92273c57a98fede188a3f1a59b1f888d113f9cce08649
lock_hash: 0x77c93b0632b5b6c3ef922c5b7cea208fb0a7c427a13d50e13d3fefad17e0c590                   
output:                                                                   
capacity: 0x9184e72a000                                                                                                                                                                                        
lock:                                                                                  
args: 0x …
```
> feat: Add util cell-meta subcommand

- src/plugin/builtin.rs
- src/plugin/manager.rs
- src/subcommands/account.rs
Fix https://github.com/nervosnetwork/ckb-cli/issues/325
> fix: Fix default keystore require password

- ckb-sdk/src/transaction.rs
- ckb-sdk/src/tx_helper.rs
- src/subcommands/dao/mod.rs
Fix: https://github.com/nervosnetwork/ckb-cli/issues/330
> feat: Update lock script group init witness to sign target transaction

- src/subcommands/api_server.rs
- src/subcommands/wallet/mod.rs
- test/src/spec/wallet.rs
```
wallet transfer \
--privkey-path <privkey> \
--to-address <address> \
--capacity 180 \
--tx-fee 0.0001 \
--skip-check-to-address
```
> feat: Skip check to-address argument with wallet transfer

- Makefile
- ckb-index/src/index/mod.rs
- ckb-index/src/index/types.rs
- ckb-index/src/lib.rs
- ckb-sdk-types/src/lib.rs
- ckb-sdk/src/lib.rs
- src/interactive.rs
- src/main.rs
- src/subcommands/dao/mod.rs
- src/subcommands/index.rs
- src/subcommands/mod.rs
- src/subcommands/wallet/index.rs
- src/subcommands/wallet/mod.rs
- src/utils/index.rs
* Detect long fork from index database and log an error level message
* Rebuild current index database though sub-command
> feat: Indexer detect long fork

- Cargo.lock
- Cargo.toml
- Makefile
- ckb-index/Cargo.toml
- ckb-sdk-types/Cargo.toml
- ckb-sdk-types/src/transaction.rs
- ckb-sdk/Cargo.toml
- ckb-sdk/src/rpc/client.rs
- ckb-sdk/src/rpc/types.rs
- ckb-sdk/src/transaction.rs
- plugin-protocol/Cargo.toml
- src/subcommands/rpc.rs
- test/Cargo.toml
- test/src/spec/dao.rs
* Update ckb to v0.39.0-rc2
* Add get_consensus and get_raw_tx_pool rpc methods
> chore: Update ckb to v0.39

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- Makefile
- ckb-index/Cargo.toml
- ckb-sdk-types/Cargo.toml
- ckb-sdk/Cargo.toml
- ckb-sdk/src/rpc/types.rs
- deny.toml
- plugin-protocol/Cargo.toml
- plugin-protocol/examples/keystore.rs
- plugin-protocol/examples/keystore_no_password.rs
- src/subcommands/dao/builder.rs
- src/subcommands/dao/mod.rs
- src/subcommands/dao/util.rs
- src/subcommands/mock_tx.rs
- src/subcommands/tx.rs
- src/subcommands/wallet/mod.rs
- test/Cargo.toml
- test/src/setup.rs
* Update ckb dependency to v0.101.0
* `TransactionWithStatus` structure changed
* Use `cargo deny` to check security audit and license
> chore: Update ckb to v0.101.0

- .cargo/config
- .github/workflows/package.yaml
- Cargo.lock
- Cargo.toml
- Makefile
- ckb-index/Cargo.toml
- ckb-sdk-types/Cargo.toml
- ckb-sdk/Cargo.toml
- ckb-sdk/src/rpc/client.rs
- ckb-sdk/src/rpc/mod.rs
- ckb-sdk/src/rpc/types.rs
- ckb-sdk/src/wallet/keystore/mod.rs
- ckb-sdk/src/wallet/keystore/passphrase.rs
- plugin-protocol/Cargo.toml
- plugin-protocol/src/convert.rs
- src/subcommands/dao/util.rs
- src/subcommands/rpc.rs
- test/Cargo.toml
- test/src/setup.rs
* Update ckb to v0.101.3
* Add more rpc methods
* Update faster-hex to fix arm64 build
> chore: update ckb to v0.101.3

- Cargo.lock
- Cargo.toml
- Makefile
- ckb-signer/Cargo.toml
- test/Cargo.toml
> Upgrade ckb-sdk to 3.2.0

- Cargo.lock
- Cargo.toml
- ckb-signer/Cargo.toml
- src/subcommands/deploy/mod.rs
- src/subcommands/mock_tx.rs
- src/subcommands/rpc.rs
- src/subcommands/util.rs
- src/utils/other.rs
- src/utils/rpc/client.rs
- test/Cargo.toml
Ref: https://github.com/nervosnetwork/ckb/pull/4454
Waiting: https://github.com/nervosnetwork/ckb-sdk-rust/pull/123
> Support `include_tx_pool` for `get_live_cell` commad

- Cargo.lock
- Cargo.toml
- ckb-signer/Cargo.toml
- ckb-signer/src/keystore/mod.rs
- ckb-signer/src/keystore/signer.rs
- deny.toml
- plugin-protocol/Cargo.toml
- src/plugin/builtin.rs
- src/plugin/manager.rs
- src/subcommands/account.rs
- src/subcommands/util.rs
- src/subcommands/wallet.rs
- src/utils/mock_tx_helper.rs
- src/utils/other.rs
- src/utils/rpc/types.rs
- src/utils/signer.rs
- test/Cargo.toml
waiting:
- https://github.com/nervosnetwork/ckb-sdk-rust/pull/126
- https://github.com/nervosnetwork/ckb-standalone-debugger/pull/135
> Bump ckb dependencies to v0.117.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Bump `ckb-cli` to v1.15.0
