nervosnetwork/ckb-cli

src/subcommands/wallet/mod.rs

We should use `output.type_script.code_hash == dao_type_hash` to check dao cell, but not `output.type_script.calc_script_hash()`. This bug introduced from ad626da34760d039282b9f7292fc29f5d2f22cbf

[ᚬckb-v0.20] fix: Use wrong script hash to check dao cell

---

Cargo.lock
Cargo.toml
ckb-sdk-types/Cargo.toml
ckb-sdk-types/src/lib.rs
ckb-sdk-types/src/transaction.rs
ckb-sdk/src/transaction.rs

This way if we only need MockTransaction data structure, we won't need
to include ckb-sdk which can pull in a lot of dependencies

refactor: Split mock transaction structure to separate crate

---

ckb-index/src/index/types.rs
src/subcommands/util.rs
src/subcommands/wallet/mod.rs

1. Remove duplicate command, util key-info is enough
2. Temporarily turn off `address -> lock` storage(The default single sign is not required, and may be extended to any `address -> lock` mapping in the future)
3. `arg` output is str instead of the list

fix: remove duplicate command, util key-info is enough

---

src/interactive.rs
src/main.rs
src/subcommands/wallet/mod.rs
src/utils/other.rs

https://github.com/nervosnetwork/ckb-cli/issues/199
`--wait-for-sync` is a global flag, indicates a requirement that the command must not be executing unless the index-store synchronize to tip before executing the command.

feat: Add a global flag `--wait-for-sync`

---

src/interactive.rs
src/main.rs
src/subcommands/mod.rs
src/subcommands/molecule.rs
src/subcommands/util.rs

* Add sub-command `molecule`
* Remove sub-commands 
- `util serialize-tx`
- `util deserialize-tx`
- `util serialize-script`
- `util deserialize-script`
```
CKB> molecule --help
Molecule encode/decode utilities
USAGE:
molecule [SUBCOMMAND]
SUBCOMMANDS:
decode     Decode molecule type from binary
encode     Encode molecule type from json to binary
default    Print default json structure of certain molecule type
CKB> molecule decode --help
Decode molecule type from binary
USAGE:
molecule decode --binary-hex <binary-hex> --type <type>
OPTIONS:
--type <type>                The molecule type name defined in blockchain.mol (and extra OutPointVec)
--binary-hex <binary-hex>    Binary data hex format
CKB> molecule encode --help
Encode molecule type from json to binary
USAGE:
molecule encode …
```

feat: Add molecule serialize/deserialize utils

---

ckb-sdk/src/tx_helper.rs
src/interactive.rs
src/main.rs
src/subcommands/mod.rs
src/subcommands/tx.rs
src/subcommands/wallet/mod.rs
src/utils/arg_parser.rs
src/utils/other.rs

Add a top level sub-command `tx`, which help you craft and send complex transaction with sighash/multisig lock script.
```
CKB> tx --help
Handle common sighash/multisig transaction
SUBCOMMANDS:
init                      Init a common (sighash/multisig) transaction
add-multisig-config       Add multisig config
clear-field               Remove all field items in transaction
add-input                 Add cell input (with secp/multisig lock)
add-output                Add cell output
add-signature             Add signature
info                      Show detail of this multisig transaction (capacity, tx-fee, etc.)
sign-inputs               Sign all sighash/multisig inputs in this transaction
send                      Send multisig transaction
build-multisig-address    Build multisig address …
```

feat: Add common transaction (sighash/multisig) sub-commands

---

ckb-sdk/src/lib.rs
ckb-sdk/src/tx_helper.rs
src/subcommands/tx.rs
src/subcommands/wallet/mod.rs
src/utils/arg.rs
src/utils/other.rs

``` shell
wallet transfer \
--from-account ckt1qyqdfjzl8ju2vfwjtl4mttx6me09hayzfldq8m3a0y \
--from-locked-address ckt1q3w9q60tppt7l3j7r09qcp7lxnp3vcanvgha8pmvsa3jplykxn3238390r7sv7dzgunt0yc0l7ue5usuymudkscqqqqqqqgqyq0y7qxf \
--to-address ckt1qyqg7zchpds6lv3v0nr36z2msu2x9a5lkhrq7kvyww \
--capacity 19999.9999 \
--tx-fee 0.00001
wallet transfer \
--from-account ckt1qyqd5eyygtdmwdr7ge736zw6z0ju6wsw7rssu8fcve \
--from-locked-address ckt1q3w9q60tppt7l3j7r09qcp7lxnp3vcanvgha8pmvsa3jplykxn32s08dj83qavwc4l4ceyeta2ryhkahxrndxacqqqqqqqgqyqx3vx8k \
--to-address ckt1qyqvhx2mvdyujpzhpxxk7p5p7jkl0qynqg2qrgj5el \
--capacity 1999.9998 \
--tx-fee 0.0001 \
--derive-change-address ckt1qyq8r0rrv7hlsvhj7u0l90d6zxn87luzxjys95rgrn
```

feat: Wallet transfer from time locked address

---

ckb-index/src/index/mod.rs
ckb-index/src/index/types.rs
src/interactive.rs
src/main.rs
src/subcommands/mod.rs
src/subcommands/tui/mod.rs
src/subcommands/wallet/index.rs
src/subcommands/wallet/mod.rs
src/utils/config.rs
src/utils/index.rs
src/utils/mod.rs
src/utils/other.rs

`reader.iter_from` spend too much time to scan the database (scan every 1 block), now only scan the database when need (when commit batch of blocks, which about 200 blocks). It will increase sync speed about 14 times.
Also `Fix --wait-for-sync`
```
ckb-cli rpc get_tip_block_number
108601
time ./target/release/ckb-cli --wait-for-sync wallet top-capacity
./target/release/ckb-cli --wait-for-sync wallet top-capacity  1792.77s user 98.92s system 97% cpu 32:27.96 total
time ckb-cli --wait-for-sync wallet top-capacity
ckb-cli --wait-for-sync wallet top-capacity  129.03s user 18.65s system 73% cpu 3:21.45 total
```

perf: Speed up sync index database

---

ckb-sdk/src/wallet/keystore/error.rs
ckb-sdk/src/wallet/keystore/mod.rs
src/interactive.rs
src/subcommands/account.rs

``` shell
CKB> account import-keystore --help
Import key from encrypted keystore json file and create a new account.
USAGE:
account import-keystore --path <path>
OPTIONS:
--path <path>    The keystore file path (json format)
CKB> account import-keystore --path xxx.json
Decrypt password:                                                   
Password:                                         
Repeat password: 
```

feat: Allow import keystore exported from Neuron

---

src/interactive.rs
src/main.rs
src/subcommands/util.rs
test/src/main.rs
test/src/spec/mod.rs
test/src/spec/util.rs

```
CKB> util sign-data --binary-hex 0xdeadbeef --privkey-path ../privkey
message: 0x761b06536d4d9580de9b63a3d5c5a5da0c6826c39775a7ce5039ac7e0f7f5dbc
recoverable: false
signature: 0x3f5aad8439367a7840deffbf3ee7657b9b225c553f7d5a4f766d99ac78128a6f7de732923d4dcf4551ff97421f104aa33d83d14362ab276502580cdd66fd56ee
CKB> util sign-data --binary-hex 0xdeadbeef --privkey-path ../privkey --recoverable
message: 0x761b06536d4d9580de9b63a3d5c5a5da0c6826c39775a7ce5039ac7e0f7f5dbc
recoverable: true
signature: 0x3f5aad8439367a7840deffbf3ee7657b9b225c553f7d5a4f766d99ac78128a6f7de732923d4dcf4551ff97421f104aa33d83d14362ab276502580cdd66fd56ee00
CKB> util sign-message --message 0x761b06536d4d9580de9b63a3d5c5a5da0c6826c39775a7ce5039ac7e0f7f5dbc --privkey-path ../privkey
recoverable: false
signature: …
```

feat: Sign any binary and verify by the signature

---

src/subcommands/account.rs
src/subcommands/mock_tx.rs
src/subcommands/util.rs

Only tx's is different in being of two possible lengths. It is left as
is but the rest use `arg::lock_arg`.

refactor: Deduplicate lock-arg arguments

---

ckb-sdk/src/wallet/bip32.rs
ckb-sdk/src/wallet/keystore/mod.rs
src/subcommands/account.rs
src/subcommands/dao/mod.rs
src/subcommands/tx.rs
src/subcommands/util.rs
src/subcommands/wallet/mod.rs
src/utils/other.rs

The empty derivation path naturally refers to the original key, so an extra `None` value is not needed.
Also, follow bip32 in making a few functions take any `AsRef<[ChildNumber]>`. This make the functions a bit more flexible.

refactor: `DerivationPath` is fine w/o `Option`

---

ckb-sdk/src/tx_helper.rs
src/subcommands/api_server.rs
src/subcommands/tx.rs
src/subcommands/wallet/mod.rs

It's hard to build customized tx since `ckb-cli` checks lock script and a bunch of things by default.
This PR adds a new flag `skip-check` to skip default checks, it would be helpful for script developers.

feat: add skip_check flag

---

src/subcommands/dao/builder.rs

Bug: As for change amount that is less than `MIN_SECP_CELL_CAPACITY`, the output capacity will be insufficient for the occupied capacity.
Fix issue https://github.com/nervosnetwork/ckb-cli/issues/263

fix: Handle change problem

---

src/interactive.rs
src/main.rs
src/subcommands/account.rs
src/subcommands/api_server.rs
src/subcommands/dao/command.rs
src/subcommands/dao/util.rs
src/subcommands/mock_tx.rs
src/subcommands/mod.rs
src/subcommands/molecule.rs
src/subcommands/rpc.rs
src/subcommands/tx.rs
src/subcommands/util.rs
src/subcommands/wallet/mod.rs

Changes:
- All debug information print to `stderr`
- Print a fixed message to `stderr` indicate the sub-command is success
```yaml
status: success
```
Related issues:
* https://github.com/nervosnetwork/ckb-cli/issues/286
* https://github.com/nervosnetwork/ckb-cli/issues/287
* https://github.com/nervosnetwork/ckb-cli/issues/288

feat: Unify output format and target

---

src/subcommands/util.rs
test/src/spec/util.rs

This feature is for avoiding user sign arbitrary binary data.
BREAKING CHANGE: Default add magic bytes before sign-data binary

feat: Add magic bytes before sign-data binary

---

Cargo.lock
Cargo.toml
Makefile
ckb-index/Cargo.toml
ckb-sdk-types/Cargo.toml
ckb-sdk/Cargo.toml
ckb-sdk/src/rpc/client.rs
ckb-sdk/src/rpc/mod.rs
ckb-sdk/src/rpc/types.rs
plugin-protocol/Cargo.toml
src/subcommands/rpc.rs
src/subcommands/tui/mod.rs
src/subcommands/tui/state.rs
test/Cargo.toml

BREAKING CHANGE: jsonrpc-types `Node` split into `LocalNode` and `RemoteNode`.

chore: Update ckb to v0.34

---

ckb-sdk/src/wallet/keystore/mod.rs
src/interactive.rs
src/main.rs
src/plugin/builtin.rs
src/subcommands/account.rs
src/subcommands/wallet/mod.rs

So, no need password to use sub-command like `account bip44-addresses`.
* Add `ckb_root` field to keystore json file
* Add `account upgrade` sub-command to update keystore json to latest format

feat: Add extended public key to keystore

---

src/plugin/manager.rs
src/subcommands/account.rs
src/subcommands/util.rs
src/subcommands/wallet/mod.rs

NOTE: Waiting https://github.com/nervosnetwork/ckb-cli/pull/313
Adding `--extended-address` to:
- `util sign-data` 
- `util sign-message`
- `util verify-message`

feat: Sign and verfiy message use extended key

---

Cargo.lock
Cargo.toml
src/subcommands/api_server.rs
src/subcommands/wallet/mod.rs
test/src/spec/wallet.rs

A typical use case is to deploy a contract with [`TYPE_ID`](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0022-transaction-structure/0022-transaction-structure.md#type-id) type script.
```shell
wallet transfer \
--privkey-path ckt1qyqp76jus2sst4qy57nnphuqgsmlmzkv2l7s8ksggy \
--to-address ckt1qyqp76jus2sst4qy57nnphuqgsmlmzkv2l7s8ksggy \
--to-data-path /path/to/contract-binary
--capacity 20000 \
--tx-fee 0.00001 \
--type-id
```

feat: Use wallet transfer to create cell with TYPE_ID type script

---

ckb-sdk/src/wallet/mod.rs
src/plugin/manager.rs
src/subcommands/account.rs
src/subcommands/dao/mod.rs
src/subcommands/tx.rs
src/subcommands/util.rs
src/subcommands/wallet/mod.rs
src/utils/other.rs

fix: Use m/44'/309'/0' as plugin keystore's root key path

---

Cargo.lock

Fixes compilation error with rust version 1.47.0
```
Compiling numext-fixed-uint-hack v0.1.4
error: expected identifier
--> /home/dllud/.cargo/registry/src/github.com-1ecc6299db9ec823/numext-fixed-uint-hack-0.1.4/src/lib.rs:33:16
|
33 |           pub fn $name(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
|                  ^^^^^
...
57 | / impl_hack!(
58 | |     (u128, U128),
59 | |     (u160, U160),
60 | |     (u224, U224),
...  |
67 | |     (u4096, U4096),
68 | | 
);
| |__- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
}
```

chore(deps): bump numext-fixed-uint from 0.1.4 to 0.1.6

---

plugin-protocol/examples/keystore.rs
plugin-protocol/examples/keystore_no_password.rs
plugin-protocol/src/convert.rs
plugin-protocol/src/lib.rs
plugin-protocol/src/method.rs
src/plugin/builtin.rs
src/plugin/manager.rs
src/subcommands/account.rs
test/src/spec/plugin.rs

`import-from-plugin` subcommand import the public key and chain code of `m/44'/309'/0'` to local file system, so we can use this information do public key derivation without the permission of ledger device. The ledger plugin save this information in `~/.ckb-cli/ledger-keystore/`

feat: Add account import-from-plugin sub-command

---

ckb-index/src/lib.rs
src/main.rs
src/plugin/builtin.rs
src/plugin/manager.rs

* Fix `account bip44-addresses` subcommand force require password
* Handle get account list from plugin failed
* Check account existence before send keystore request

fix: Improve keystore actions

---

ckb-sdk/src/wallet/keystore/mod.rs
src/subcommands/account.rs

Fix issue #366 
```
$ ./target/debug/ckb-cli account remove --lock-arg 0x1111111111111111111111111111111111111111
WARNING: please remove it CAREFULLY! Once you remove it you may lost all cells owned by this key and it's sub-keys
filepath: /home/weet/.ckb-cli/keystore/UTC--2020-99-99T03-54-24.111111111Z--1111111111111111111111111111111111111111
```

feat: Add account remove sub-command

---

src/subcommands/wallet/mod.rs

```
Invalid to-address: ckt1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqchfq7c4e0e864p98x0t7mc0k58thz83sgam75j
[Hint]: Add `--skip-check-to-address` flag to transfer to any address 
```

chore: improve error message in wallet transfer subcommand

---

.github/workflows/package.yaml

* Do not mount .cargo
* Centos-7 builder will enable the toolset using entrypoint, so we don't need to call `scl enable` here.

chore: change release package command

---

src/subcommands/molecule.rs
src/utils/arg_parser.rs

fix: use from_compatible_slice to decode molecule binary data

---

src/subcommands/util.rs
test/src/main.rs
test/src/spec/util.rs

```
$ ckb-cli util address-info --address ckt1qr0wcya8hrssq4u4gyuyejh5k53rwvly54yrcwhvjhwufsw4afdjyq2vctn9ycsy4e4zar70ztm663e0gxskqm2mjcjta67jzhtcpqyld2gsf0g0e5kgd7q5qlm25zvpstx8vgdk6q8qat7q
extra:
address-type: Full
data-encoding: bech32m
lock_script:
args: 0x4cc2e6526204ae6a2e8fcf12f7ad472f41a1606d5b9624beebd215d780809f6a9104bd0fcd2c86f81407f6aa098182cc7621b6d0
code_hash: 0xdeec13a7b8e100579541384ccaf4b5223733e4a5483c3aec95ddc4c1d5ea5b22
hash_type: type
network: ckb_testnet
```

feat: add `util address-info` subcommand

---

Cargo.lock
Cargo.toml
src/deployment.toml
src/interactive.rs
src/main.rs
src/plugin/builtin.rs
src/subcommands/deploy/deployment.rs
src/subcommands/deploy/intermedium_info.rs
src/subcommands/deploy/mod.rs
src/subcommands/deploy/state_change.rs
src/subcommands/deploy/tx_builder.rs
src/subcommands/mod.rs
src/subcommands/tx.rs
src/subcommands/util.rs
src/utils/arg_parser.rs
src/utils/other.rs
src/utils/tx_helper.rs

* sighash/multisig lock/unlock
* type id
* dep group
* migration
* outpoint/file as data source
* offline sign
```bash
ckb-cli deploy init-config --deployment-config deployment.toml
ckb-cli deploy gen-txs \
--deployment-config ./deployment.toml \
--migration-dir ./migrations \
--from-address ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37 \
--sign-now \
--info-file info.json
ckb-cli deploy sign-txs \
--from-account ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37 \
--add-signatures \
--info-file info.json 
ckb-cli deploy sign-txs \
--from-account ckt1qyqyqnuss20vpevzrt46n0886h5yrn5l07jsgz7kfp \
--add-signatures \
--info-file info.json 
ckb-cli deploy explain-txs --info-file info.json
ckb-cli deploy apply-txs \
--migration-dir ./migrations \
--info-file info.json
```

feat: add deploy subcommand

---

src/subcommands/api_server.rs
src/subcommands/dao/command.rs
src/subcommands/dao/mod.rs
src/subcommands/sudt.rs
src/subcommands/util.rs
src/subcommands/wallet.rs
src/utils/arg.rs
src/utils/other.rs

- Add parameter force-small-change-as-fee to `wallet transfer`.
- Remove `conflicts_with` parameter `lock-hash`, so `wallet get-capacity` won't break on debug mode.

fix: Fix 2 problems of wallet subcommands

---

Cargo.lock
Cargo.toml
ckb-signer/Cargo.toml
ckb-signer/src/keystore/mod.rs
src/subcommands/util.rs
src/utils/rpc/primitive.rs

* bump up ckb-cli to v1.3.0
* bump up ckb-signer to v0.3.1
* fix clippy
* cargo update

chore: bump up ckb-cli to v1.3.0

---

Cargo.lock
Cargo.toml
Makefile

CKB v0.105.1 has been yanked.
Closes #547 #545
This PR also upgrades crossbeam-channel to bypass the security checking by CI.

chore(ci): use ckb v0.106.0 in integration test

---

.github/workflows/package.yaml

Add a job `package-for-macos-silicon` in the workflow package.yaml to
generate binaries for Apple Silicon using self hosted runner.
Closes #539

chore(ci): generate binaries for Apple Silicon

---

Cargo.lock
src/subcommands/util.rs

[Fix] Type of `secp256k1_data.out_point.index` for `ckb util genesis-scripts` should be hex encoded

---

ckb-signer/src/keystore/mod.rs
src/subcommands/account.rs
src/utils/other.rs
test/src/main.rs
test/src/setup.rs
test/src/spec/account_keystore_perm.rs
test/src/spec/mod.rs

This PR want to:
Request for review: @zhangsoledad @doitian

Fix directory and files permission on `unix` platform

---

Cargo.lock
README.md
src/subcommands/rpc.rs
src/utils/rpc/client.rs
src/utils/rpc/mod.rs
src/utils/rpc/types.rs

issue: 
- https://github.com/nervosnetwork/ckb-cli/issues/578
This PR introduces new subcommands for the CKB Indexer RPC. The following commands have been added to enhance functionality and user interaction:
- `get_indexer_tip`: This command retrieves the latest tip from the indexer.
- `get_cells`: This command fetches live cells based on specified conditions.
- `get_transactions`: This command retrieves transactions based on given parameters.
- `get_cells_capacity`: This command calculates and returns the total capacity of the live cells.

feat: addition of subcommands for CKB Indexer RPC

---

src/utils/other.rs

When checking if a cell is alive, pending transactions associated with the cell should also be considered live.
In order to construct chained transactions.

fix construct chained transaction failed when the previous transaction is in a pending state.

---

src/subcommands/deploy/deployment.rs
src/subcommands/deploy/mod.rs
src/subcommands/tx.rs

Deploy with multisig will output `invalid address` error if address isn't `Short`.
This PR fixed the issue by copy the parsing code from https://github.com/nervosnetwork/ckb-cli/blob/develop/src/subcommands/tx.rs#L575

Fix deploy with multisig

---

.github/workflows/package.yaml

Declare `contents: write` for actions/create-release, actions/upload-release-asset

ci: declare permissions in package workflow

---

README.md
src/subcommands/tx.rs

In the readme, the example titled `Example: Indexer get cells (yaml output format)` shows the `get_transactions` method.
- Added example of indexer `get_cells`
- Added the title of indexer `get transactions`
Related issue: 
- https://github.com/nervosnetwork/ckb-cli/issues/594

fix example in readme.

---

Cargo.lock
Cargo.toml
ckb-signer/Cargo.toml
plugin-protocol/Cargo.toml
src/subcommands/rpc.rs
src/utils/rpc/client.rs
src/utils/rpc/types.rs
test/Cargo.toml

Need 
- https://github.com/nervosnetwork/ckb-standalone-debugger/pull/130
- https://github.com/nervosnetwork/ckb-sdk-rust/pull/115

Bump ckb dependencies to v0.116.0

---

src/subcommands/rpc.rs

The arg name is wrong, rename it to `--num-epochs`.

fix: fix rpc generate_epochs arg name

---

Cargo.lock

```
error[vulnerability]: `MemBio::get_buf` has undefined behavior with empty buffers
┌─ /home/runner/work/ckb/ckb/Cargo.lock:313:1
│
313 │ openssl 0.10.64 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2024-0357
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0357
= Previously, `MemBio::get_buf` called `slice::from_raw_parts` with a null-pointer, which violates the functions invariants, leading to undefined behavior. In debug builds this would produce an assertion failure. This is now fixed.
= Announcement: https://github.com/sfackler/rust-openssl/pull/2266
= Solution: Upgrade to >=0.10.66 (try `cargo update -p openssl`)
```

chore(deps): upgrade openssl crate

---

.github/workflows/package.yaml

Use ckb-docker-builder rust-1.75.0 to package ckb-cli
Issue Number: close nervosnetwork/ckb#4550 #609 #612
Problem Summary: When no git information was found, the sub-command --version outputs a pair of empty brackets.

fix: empty git commit version of cli

---

src/utils/rpc/types.rs

Complete get-transaction rpc subcommand

---

src/subcommands/mod.rs
src/utils/tx_helper.rs

Only allow the --zero-lock to activate when the script match 3 condition:
- code_hash: 0x000...000 (all zero)
- hash_type: data
- args: 0x

`--zero-lock` only activate when code_hash is zero & hash_type is data and args is 0x

---

src/subcommands/deploy/mod.rs
src/subcommands/mock_tx.rs
src/subcommands/mod.rs
src/subcommands/rpc.rs
src/subcommands/tx.rs
src/utils/tx_helper.rs

This PR:
- Allow `data`, `data1` and `data2` for `--zero-lock` flag.
- remove useless `--zero-lock` flag on `tx add-input`.
Test: 
1. launch a ckb dev chain node. In ckb.toml, add `"Indexer"` to rpc_modules
2. create a deployment.toml
```toml
[[cells]]
name = "my_zero"
enable_type_id = false
location = { file = "zero/build/release/first-contract" }
[lock]
code_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
args = "0x"
hash_type = "data1"
```
3. run the test.sh to deploy the zero-lock contract:
```bash
#!/usr/bin/env bash
set -ex
ACCOUNT=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwgx292hnvmn68xf779vmzrshpmm6epn4c0cgwga
rm info.json || true
rm -rf migrations; mkdir migrations
PASSWORD=${PASSWORD}
echo $PASSWORD | ./ckb-cli deploy gen-txs \ …
```

allow `data1` and `data2` for `--zero-lock`
